server:
  port: 8000
  error:
    include-message: always
spring:
  application:
    name: multitenancy
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true